// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID          *int          `json:"id"`
	Name        string        `json:"name"`
	Classifieds []*Classified `json:"classifieds"`
}

type Classified struct {
	ID        int       `json:"id"`
	Title     string    `json:"title"`
	Price     float64   `json:"Price"`
	CreatedAt string    `json:"created_at"`
	Category  *Category `json:"category"`
}
